# Generated by Django 4.2.11 on 2024-03-25 18:04

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(help_text='Enter Username', max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter Password', max_length=20)),
                ('fname', models.CharField(help_text='Enter First Name', max_length=20)),
                ('lname', models.CharField(help_text='Enter Last Name', max_length=20)),
                ('billAddr', models.CharField(help_text='Enter Billing Address', max_length=50)),
                ('email', models.EmailField(help_text='Enter Email Address', max_length=40)),
            ],
            options={
                'ordering': ['userID'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('userID'), name='userID_case_insensitive_unique', violation_error_message='Username already exists'),
        ),
    ]
