# Generated by Django 4.2.11 on 2024-03-28 23:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter Password', max_length=20)),
                ('fname', models.CharField(help_text='Enter First Name', max_length=20)),
                ('lname', models.CharField(help_text='Enter Last Name', max_length=20)),
                ('email', models.EmailField(help_text='Enter Email Address', max_length=40)),
            ],
            options={
                'ordering': ['adminID'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(default='inventory_images/default.jpg', upload_to='inventory_images/')),
            ],
            options={
                'ordering': ['isbn'],
            },
        ),
        migrations.CreateModel(
            name='OrderHist',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('dateOrdered', models.DateField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numItems', models.IntegerField()),
            ],
            options={
                'ordering': ['dateOrdered'],
            },
        ),
        migrations.CreateModel(
            name='PrevSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['orderID'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerID', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter Password', max_length=20)),
                ('name', models.CharField(help_text='Enter Name', max_length=20)),
                ('email', models.EmailField(help_text='Enter Email Address', max_length=40)),
                ('address', models.CharField(help_text='Enter Address', max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['sellerID'],
            },
        ),
        migrations.CreateModel(
            name='SellerReq',
            fields=[
                ('requestID', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('dateApplied', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dateApplied'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['userID'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(help_text='Enter Username', max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter Password', max_length=20)),
                ('fname', models.CharField(help_text='Enter First Name', max_length=20)),
                ('lname', models.CharField(help_text='Enter Last Name', max_length=20)),
                ('billAddr', models.CharField(help_text='Enter Billing Address', max_length=50)),
                ('email', models.EmailField(help_text='Enter Email Address', max_length=40)),
            ],
            options={
                'ordering': ['userID'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('userID'), name='userID_case_insensitive_unique', violation_error_message='Username already exists'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbn_cart', to='store.inventory'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cart', to='store.inventory'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user'),
        ),
        migrations.AddField(
            model_name='sellerreq',
            name='sellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.seller'),
        ),
        migrations.AddField(
            model_name='prevsold',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='isbn_sold', to='store.inventory'),
        ),
        migrations.AddField(
            model_name='prevsold',
            name='orderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.orderhist'),
        ),
        migrations.AddField(
            model_name='prevsold',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='price_sold', to='store.inventory'),
        ),
        migrations.AddField(
            model_name='prevsold',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.user'),
        ),
        migrations.AddField(
            model_name='orderhist',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.user'),
        ),
    ]
