# Generated by Django 4.2.11 on 2024-03-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter Password', max_length=20)),
                ('fname', models.CharField(help_text='Enter First Name', max_length=20)),
                ('lname', models.CharField(help_text='Enter Last Name', max_length=20)),
                ('email', models.EmailField(help_text='Enter Email Address', max_length=40)),
            ],
            options={
                'ordering': ['adminID'],
            },
        ),
    ]
