# Generated by Django 4.2.11 on 2024-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Enter Name', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller')], default='CUSTOMER', help_text='Type', max_length=50),
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
