# Generated by Django 4.2.11 on 2024-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='adminID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
