# Generated by Django 4.2.11 on 2024-03-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_admin_adminid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerID', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter Password', max_length=20)),
                ('name', models.CharField(help_text='Enter Name', max_length=20)),
                ('email', models.EmailField(help_text='Enter Email Address', max_length=40)),
                ('address', models.CharField(help_text='Enter Address', max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['sellerID'],
            },
        ),
    ]
