# Generated by Django 4.2.11 on 2024-03-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellerReq',
            fields=[
                ('requestID', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('dateApplied', models.DateField(auto_now_add=True)),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.seller')),
            ],
            options={
                'ordering': ['dateApplied'],
            },
        ),
    ]
