# Generated by Django 4.2.11 on 2024-04-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customermore_sellermore_customer_seller_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhist',
            options={'ordering': ['orderID']},
        ),
        migrations.RenameField(
            model_name='sellermore',
            old_name='userID',
            new_name='sellerID',
        ),
        migrations.RemoveField(
            model_name='orderhist',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orderhist',
            name='numItems',
        ),
        migrations.AddField(
            model_name='orderhist',
            name='isbn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='isbn_sold', to='store.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhist',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='price_sold', to='store.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhist',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrevSold',
        ),
    ]
