# Generated by Django 4.2.11 on 2024-03-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_inventory_orderhist'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbn_cart', to='store.inventory')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cart', to='store.inventory')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
            options={
                'ordering': ['userID'],
            },
        ),
        migrations.CreateModel(
            name='PrevSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='isbn_sold', to='store.inventory')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.orderhist')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='price_sold', to='store.inventory')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.user')),
            ],
            options={
                'ordering': ['orderID'],
            },
        ),
    ]
