# Generated by Django 4.2.11 on 2024-03-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shoppingcart_prevsold'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(default='inventory_images/default.jpg', upload_to='inventory_images/'),
        ),
    ]
