# Generated by Django 4.2.11 on 2024-04-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customermore_credit_sellermore_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='customermore',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customermore',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customermore',
            name='fname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customermore',
            name='lname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
