# Generated by Django 4.2.11 on 2024-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_seller_alter_sellerreq_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermore',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellermore',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sellermore',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
