# Generated by Django 4.2.11 on 2024-04-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_sellermore_address_alter_sellermore_credit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerMore',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='SellerMore',
            new_name='Seller',
        ),
    ]
